#ifndef CONFIG_H
#define CONFIG_H
/*
SOFTWARE VERSION
----------------
THESE DEFINES INDICATE THE CURRENT SOFTWARE 
1. VERSION: THIS IS THE CURRENT VERSION DISPLAYED AS 3 DIGITS (1 MAJOR, 1MINOR, 1BUGFIX) and a letter d(DEBUG) r(release) t(test)
2. COMPILE TIME: AUTOMATIC
3. COMPILE DATE: AUTOMATIC
*/
#define VERSION "d0.1.0"
#define COMPILE_DATE __DATE__
#define COMPILE_TIME __TIME__


#endif // DEFINES_H